/**
 * Static demo datasets for feature-gate preview mode.
 *
 * Shown to Observer (free) users behind a blurred overlay so they can
 * preview what the platform looks like with real-ish governance data.
 *
 * All content is in French and relates to AI governance themes.
 * IDs use the "demo-" prefix; organization_id is always "demo-org".
 */

import type {
  RiskAssessment,
  ComplianceAssessment,
  RemediationAction,
  AutomatedDecision,
  Contestation,
  GovernancePolicy,
  GovernanceRole,
  GovernanceCommittee,
  Incident,
  MonitoringMetric,
  MonitoringDataPoint,
  Decision,
  GovDocument,
  Dataset,
  DataTransfer,
  BiasFinding,
  Vendor,
} from '@/types/database';

/* ================================================================== */
/*  1. RISK ASSESSMENTS                                                */
/* ================================================================== */

type AssessmentRow = RiskAssessment & { ai_systems: { name: string } };

export const DEMO_RISK_ASSESSMENTS: AssessmentRow[] = [
  {
    id: 'demo-ra-1',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-1',
    total_score: 72,
    risk_level: 'high' as const,
    answers: {},
    requirements: {},
    probability: 'likely',
    impact: 'significant',
    status: 'approved' as const,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-18T14:30:00Z',
    ai_systems: { name: 'Système de scoring RH' },
  },
  {
    id: 'demo-ra-2',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-2',
    total_score: 35,
    risk_level: 'limited' as const,
    answers: {},
    requirements: {},
    probability: 'possible',
    impact: 'minor',
    status: 'submitted' as const,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-12T10:15:00Z',
    updated_at: '2026-01-20T11:00:00Z',
    ai_systems: { name: 'Chatbot service client' },
  },
  {
    id: 'demo-ra-3',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-3',
    total_score: 88,
    risk_level: 'critical' as const,
    answers: {},
    requirements: {},
    probability: 'almost_certain',
    impact: 'critical',
    status: 'in_review' as const,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T08:00:00Z',
    updated_at: '2026-01-22T16:45:00Z',
    ai_systems: { name: 'Détection de fraude financière' },
  },
  {
    id: 'demo-ra-4',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-4',
    total_score: 18,
    risk_level: 'minimal' as const,
    answers: {},
    requirements: {},
    probability: 'rare',
    impact: 'negligible',
    status: 'draft' as const,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-20T13:00:00Z',
    updated_at: '2026-01-25T09:30:00Z',
    ai_systems: { name: 'Traduction automatique interne' },
  },
];

/* ================================================================== */
/*  2. COMPLIANCE SCORES                                               */
/* ================================================================== */

export const DEMO_COMPLIANCE_SCORES = {
  global: 64,
  frameworks: [
    {
      framework: 'eu_ai_act',
      score: 58,
      compliant: 12,
      partial: 8,
      nonCompliant: 5,
      notApplicable: 3,
    },
    {
      framework: 'iso_42001',
      score: 71,
      compliant: 18,
      partial: 6,
      nonCompliant: 2,
      notApplicable: 4,
    },
    {
      framework: 'nist_ai_rmf',
      score: 63,
      compliant: 14,
      partial: 9,
      nonCompliant: 4,
      notApplicable: 3,
    },
  ],
} as const;

/* ================================================================== */
/*  3. COMPLIANCE ASSESSMENTS                                          */
/* ================================================================== */

export const DEMO_COMPLIANCE_ASSESSMENTS: ComplianceAssessment[] = [
  {
    id: 'demo-ca-1',
    organization_id: 'demo-org',
    framework_code: 'eu_ai_act',
    requirement_code: 'AIA-ART9-1',
    status: 'compliant' as const,
    responsible_user_id: 'demo-user-1',
    comments: null,
    last_verified_at: '2026-01-15T10:00:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'demo-ca-2',
    organization_id: 'demo-org',
    framework_code: 'iso_42001',
    requirement_code: 'ISO42-5.2',
    status: 'partially_compliant' as const,
    responsible_user_id: 'demo-user-2',
    comments: null,
    last_verified_at: '2026-01-18T14:00:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-08T11:00:00Z',
    updated_at: '2026-01-18T14:00:00Z',
  },
  {
    id: 'demo-ca-3',
    organization_id: 'demo-org',
    framework_code: 'nist_ai_rmf',
    requirement_code: 'NIST-GOV-1.1',
    status: 'non_compliant' as const,
    responsible_user_id: 'demo-user-1',
    comments: null,
    last_verified_at: '2026-01-20T09:30:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-20T09:30:00Z',
  },
];

/* ================================================================== */
/*  4. REMEDIATION ACTIONS                                             */
/* ================================================================== */

export const DEMO_REMEDIATION_ACTIONS: RemediationAction[] = [
  {
    id: 'demo-rem-1',
    organization_id: 'demo-org',
    assessment_id: 'demo-ca-2',
    title: 'Compléter la documentation du système de management de l\u2019IA',
    description: null,
    responsible_user_id: 'demo-user-2',
    due_date: '2026-03-15',
    priority: 'high' as const,
    status: 'in_progress' as const,
    notes: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-19T10:00:00Z',
    updated_at: '2026-01-25T16:00:00Z',
  },
  {
    id: 'demo-rem-2',
    organization_id: 'demo-org',
    assessment_id: 'demo-ca-3',
    title: 'Mettre en place le cadre de gouvernance IA selon NIST',
    description: null,
    responsible_user_id: 'demo-user-1',
    due_date: '2026-04-01',
    priority: 'critical' as const,
    status: 'planned' as const,
    notes: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-21T08:00:00Z',
    updated_at: '2026-01-21T08:00:00Z',
  },
];

/* ================================================================== */
/*  5. AUTOMATED DECISIONS                                             */
/* ================================================================== */

export const DEMO_AUTOMATED_DECISIONS: AutomatedDecision[] = [
  {
    id: 'demo-ad-1',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-1',
    decision_type: 'Présélection de candidatures',
    automation_level: 'fully_automated' as const,
    affected_persons: ['Candidats', 'Employés internes'],
    decision_impact: 'high' as const,
    information_channel: null,
    explanation_enabled: true,
    contestation_enabled: true,
    legal_basis: 'legitimate_interest',
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-08T09:00:00Z',
    updated_at: '2026-01-22T11:00:00Z',
  },
  {
    id: 'demo-ad-2',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-3',
    decision_type: 'Blocage de transactions suspectes',
    automation_level: 'semi_automated' as const,
    affected_persons: ['Clients', 'Partenaires commerciaux'],
    decision_impact: 'medium' as const,
    information_channel: null,
    explanation_enabled: true,
    contestation_enabled: false,
    legal_basis: 'legal_obligation',
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-10T14:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
];

/* ================================================================== */
/*  6. CONTESTATIONS                                                   */
/* ================================================================== */

export const DEMO_CONTESTATIONS: Contestation[] = [
  {
    id: 'demo-cont-1',
    organization_id: 'demo-org',
    case_number: 'CONT-2026-001',
    ai_system_id: 'demo-sys-1',
    requester_name: 'Marie Dupont',
    requester_email: 'marie.dupont@example.com',
    requester_phone: null,
    received_at: '2026-01-25T09:00:00Z',
    reception_channel: 'email',
    contested_decision_description: 'Rejet automatique de candidature au poste de développeur senior',
    contestation_reason: 'Le système a rejeté ma candidature sans tenir compte de mon expérience pertinente en IA',
    requester_observations: null,
    assigned_to: 'demo-user-1',
    analysis: null,
    review_outcome: null,
    justification: null,
    revised_decision: null,
    decision_date: null,
    status: 'under_review' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-25T09:00:00Z',
    updated_at: '2026-01-28T14:00:00Z',
  },
];

/* ================================================================== */
/*  7. GOVERNANCE POLICIES                                             */
/* ================================================================== */

export const DEMO_POLICIES: GovernancePolicy[] = [
  {
    id: 'demo-pol-1',
    organization_id: 'demo-org',
    title: 'Politique d\u2019utilisation responsable de l\u2019IA',
    description: null,
    policy_type: 'ai_usage' as const,
    content: 'Cette politique encadre l\u2019usage des systèmes d\u2019intelligence artificielle au sein de l\u2019organisation.',
    version: 2,
    parent_id: null,
    status: 'published' as const,
    published_at: '2026-01-10T10:00:00Z',
    published_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-11-01T09:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'demo-pol-2',
    organization_id: 'demo-org',
    title: 'Procédure d\u2019approbation des systèmes IA',
    description: null,
    policy_type: 'approval_procedure' as const,
    content: 'Tout nouveau système d\u2019IA doit passer par un processus d\u2019approbation en trois étapes.',
    version: 1,
    parent_id: null,
    status: 'in_review' as const,
    published_at: null,
    published_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T11:00:00Z',
    updated_at: '2026-01-20T15:00:00Z',
  },
  {
    id: 'demo-pol-3',
    organization_id: 'demo-org',
    title: 'Charte éthique de l\u2019IA générative',
    description: null,
    policy_type: 'ethics_charter' as const,
    content: 'La présente charte définit les principes éthiques guidant l\u2019usage de l\u2019IA générative.',
    version: 1,
    parent_id: null,
    status: 'draft' as const,
    published_at: null,
    published_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-01-22T14:00:00Z',
  },
];

/* ================================================================== */
/*  8. GOVERNANCE ROLES                                                */
/* ================================================================== */

export const DEMO_GOVERNANCE_ROLES: GovernanceRole[] = [
  {
    id: 'demo-gr-1',
    organization_id: 'demo-org',
    role_type: 'ai_lead' as const,
    user_id: 'demo-user-1',
    mandate: null,
    nominated_at: '2026-01-05T09:00:00Z',
    scope: 'global' as const,
    ai_system_id: null,
    status: 'active',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-01-05T09:00:00Z',
  },
  {
    id: 'demo-gr-2',
    organization_id: 'demo-org',
    role_type: 'privacy_officer' as const,
    user_id: 'demo-user-2',
    mandate: null,
    nominated_at: '2026-01-06T10:00:00Z',
    scope: 'global' as const,
    ai_system_id: null,
    status: 'active',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-06T10:00:00Z',
    updated_at: '2026-01-06T10:00:00Z',
  },
  {
    id: 'demo-gr-3',
    organization_id: 'demo-org',
    role_type: 'risk_officer' as const,
    user_id: 'demo-user-3',
    mandate: null,
    nominated_at: '2026-01-07T11:00:00Z',
    scope: 'per_system' as const,
    ai_system_id: 'demo-sys-1',
    status: 'active',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-07T11:00:00Z',
    updated_at: '2026-01-07T11:00:00Z',
  },
];

/* ================================================================== */
/*  9. GOVERNANCE COMMITTEES                                           */
/* ================================================================== */

export const DEMO_COMMITTEES: GovernanceCommittee[] = [
  {
    id: 'demo-gc-1',
    organization_id: 'demo-org',
    name: 'Comité d\u2019éthique IA',
    mandate: null,
    meeting_frequency: 'monthly' as const,
    members: [],
    status: 'active',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-03T09:00:00Z',
    updated_at: '2026-01-03T09:00:00Z',
  },
  {
    id: 'demo-gc-2',
    organization_id: 'demo-org',
    name: 'Comité de pilotage des systèmes IA',
    mandate: null,
    meeting_frequency: 'quarterly' as const,
    members: [],
    status: 'active',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-04T10:00:00Z',
    updated_at: '2026-01-04T10:00:00Z',
  },
];

/* ================================================================== */
/*  10. INCIDENTS                                                      */
/* ================================================================== */

export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 'demo-inc-1',
    organization_id: 'demo-org',
    title: 'Biais détecté dans le scoring RH',
    category: 'ai' as const,
    incident_type: 'bias',
    ai_system_id: 'demo-sys-1',
    description: 'Un biais de genre a été détecté dans les scores de présélection des candidatures.',
    detected_at: '2026-01-15T08:30:00Z',
    started_at: null,
    detection_mode: 'monitoring',
    severity: 'high' as const,
    assigned_to: 'demo-user-1',
    impact_description: null,
    affected_count: null,
    priority: 'high',
    serious_harm_risk: false,
    root_cause: null,
    contributing_factors: [],
    resolution_date: null,
    corrective_actions: [],
    post_mortem: null,
    lessons_learned: null,
    status: 'investigating' as const,
    cai_notification_status: null,
    cai_notified_at: null,
    persons_notified: false,
    reported_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-15T08:30:00Z',
    updated_at: '2026-01-20T16:00:00Z',
    deleted_at: null,
  },
  {
    id: 'demo-inc-2',
    organization_id: 'demo-org',
    title: 'Fuite de données personnelles via le chatbot',
    category: 'privacy' as const,
    incident_type: 'data_leak',
    ai_system_id: 'demo-sys-2',
    description: 'Le chatbot a exposé des informations personnelles d\u2019un client dans une réponse générée.',
    detected_at: '2026-01-18T14:00:00Z',
    started_at: null,
    detection_mode: 'user_report',
    severity: 'critical' as const,
    assigned_to: 'demo-user-2',
    impact_description: null,
    affected_count: null,
    priority: 'critical',
    serious_harm_risk: true,
    root_cause: null,
    contributing_factors: [],
    resolution_date: null,
    corrective_actions: [],
    post_mortem: null,
    lessons_learned: null,
    status: 'resolving' as const,
    cai_notification_status: null,
    cai_notified_at: null,
    persons_notified: false,
    reported_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-18T14:00:00Z',
    updated_at: '2026-01-22T10:00:00Z',
    deleted_at: null,
  },
  {
    id: 'demo-inc-3',
    organization_id: 'demo-org',
    title: 'Taux de faux positifs anormalement élevé',
    category: 'ai' as const,
    incident_type: 'performance_degradation',
    ai_system_id: 'demo-sys-3',
    description: 'Le système de détection de fraude génère un taux de faux positifs de 45%, bloquant des transactions légitimes.',
    detected_at: '2026-01-20T11:00:00Z',
    started_at: null,
    detection_mode: 'monitoring',
    severity: 'medium' as const,
    assigned_to: 'demo-user-3',
    impact_description: null,
    affected_count: null,
    priority: 'medium',
    serious_harm_risk: false,
    root_cause: null,
    contributing_factors: [],
    resolution_date: null,
    corrective_actions: [],
    post_mortem: null,
    lessons_learned: null,
    status: 'triaged' as const,
    cai_notification_status: null,
    cai_notified_at: null,
    persons_notified: false,
    reported_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-01-21T09:00:00Z',
    deleted_at: null,
  },
  {
    id: 'demo-inc-4',
    organization_id: 'demo-org',
    title: 'Erreur de traduction dans un document contractuel',
    category: 'ai' as const,
    incident_type: 'output_error',
    ai_system_id: 'demo-sys-4',
    description: 'Le système de traduction a produit une erreur de sens dans un paragraphe juridique critique.',
    detected_at: '2026-01-22T16:30:00Z',
    started_at: null,
    detection_mode: 'manual_review',
    severity: 'low' as const,
    assigned_to: null,
    impact_description: null,
    affected_count: null,
    priority: 'low',
    serious_harm_risk: false,
    root_cause: null,
    contributing_factors: [],
    resolution_date: '2026-01-23T10:00:00Z',
    corrective_actions: [],
    post_mortem: null,
    lessons_learned: null,
    status: 'resolved' as const,
    cai_notification_status: null,
    cai_notified_at: null,
    persons_notified: false,
    reported_by: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-22T16:30:00Z',
    updated_at: '2026-01-23T10:00:00Z',
    deleted_at: null,
  },
];

/* ================================================================== */
/*  11. MONITORING METRICS                                             */
/* ================================================================== */

export const DEMO_MONITORING_METRICS: MonitoringMetric[] = [
  {
    id: 'demo-mm-1',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-1',
    name: 'Précision du modèle de scoring',
    category: 'performance' as const,
    unit: '%',
    direction: 'higher_is_better' as const,
    target_value: 92,
    warning_threshold: 85,
    critical_threshold: 75,
    acceptable_min: null,
    acceptable_max: null,
    collection_frequency: 'daily' as const,
    source: 'api_webhook' as const,
    is_active: true,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-01-05T09:00:00Z',
  },
  {
    id: 'demo-mm-2',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-2',
    name: 'Temps de réponse moyen du chatbot',
    category: 'latency' as const,
    unit: 'ms',
    direction: 'lower_is_better' as const,
    target_value: 500,
    warning_threshold: 1200,
    critical_threshold: 3000,
    acceptable_min: null,
    acceptable_max: null,
    collection_frequency: 'hourly' as const,
    source: 'api_webhook' as const,
    is_active: true,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-06T10:00:00Z',
    updated_at: '2026-01-06T10:00:00Z',
  },
  {
    id: 'demo-mm-3',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-3',
    name: 'Dérive des données d\u2019entraînement',
    category: 'drift_data' as const,
    unit: 'score',
    direction: 'lower_is_better' as const,
    target_value: 0.05,
    warning_threshold: 0.15,
    critical_threshold: 0.3,
    acceptable_min: null,
    acceptable_max: null,
    collection_frequency: 'weekly' as const,
    source: 'scheduled_report' as const,
    is_active: true,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-07T08:00:00Z',
    updated_at: '2026-01-07T08:00:00Z',
  },
];

/* ================================================================== */
/*  12. MONITORING DATA POINTS                                         */
/* ================================================================== */

export const DEMO_MONITORING_DATA_POINTS: MonitoringDataPoint[] = [
  {
    id: 'demo-mdp-1',
    organization_id: 'demo-org',
    metric_id: 'demo-mm-1',
    value: 89.2,
    recorded_at: '2026-01-25T08:00:00Z',
    alert_level: 'warning' as const,
    notes: 'Légère baisse de précision après la mise à jour du modèle',
    created_by: null,
    created_at: '2026-01-25T08:00:00Z',
  },
  {
    id: 'demo-mdp-2',
    organization_id: 'demo-org',
    metric_id: 'demo-mm-2',
    value: 620,
    recorded_at: '2026-01-25T10:00:00Z',
    alert_level: 'ok' as const,
    notes: null,
    created_by: null,
    created_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'demo-mdp-3',
    organization_id: 'demo-org',
    metric_id: 'demo-mm-3',
    value: 0.22,
    recorded_at: '2026-01-24T12:00:00Z',
    alert_level: 'critical' as const,
    notes: 'Dérive significative détectée — réévaluation nécessaire',
    created_by: null,
    created_at: '2026-01-24T12:00:00Z',
  },
];

/* ================================================================== */
/*  13. DECISIONS                                                      */
/* ================================================================== */

export const DEMO_DECISIONS: Decision[] = [
  {
    id: 'demo-dec-1',
    organization_id: 'demo-org',
    title: 'Approbation du déploiement du scoring RH',
    decision_type: 'go_nogo' as const,
    ai_system_ids: ['demo-sys-1'],
    context: 'Le système de scoring RH a terminé sa phase de test. Une évaluation des risques a été réalisée.',
    options_considered: null,
    decision_made: 'Déploiement approuvé avec conditions de suivi renforcé',
    justification: 'Le score de risque est acceptable et les mesures de mitigation sont en place.',
    residual_risks: null,
    conditions: null,
    impact: 'high' as const,
    effective_date: '2026-02-01',
    review_date: null,
    risk_assessment_id: null,
    incident_id: null,
    requester_id: 'demo-user-1',
    approver_ids: [],
    status: 'approved' as const,
    rejection_reason: null,
    approved_at: '2026-01-20T16:00:00Z',
    implemented_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-01-20T16:00:00Z',
  },
  {
    id: 'demo-dec-2',
    organization_id: 'demo-org',
    title: 'Suspension temporaire du système de détection de fraude',
    decision_type: 'suspension' as const,
    ai_system_ids: ['demo-sys-3'],
    context: 'Suite à l\u2019incident de faux positifs excessifs, une décision de suspension est demandée.',
    options_considered: null,
    decision_made: null,
    justification: null,
    residual_risks: null,
    conditions: null,
    impact: 'critical' as const,
    effective_date: null,
    review_date: null,
    risk_assessment_id: null,
    incident_id: null,
    requester_id: 'demo-user-3',
    approver_ids: [],
    status: 'in_review' as const,
    rejection_reason: null,
    approved_at: null,
    implemented_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-21T10:00:00Z',
    updated_at: '2026-01-23T14:00:00Z',
  },
  {
    id: 'demo-dec-3',
    organization_id: 'demo-org',
    title: 'Changement de fournisseur pour le chatbot',
    decision_type: 'vendor_change' as const,
    ai_system_ids: ['demo-sys-2'],
    context: 'Le fournisseur actuel ne respecte pas les exigences de confidentialité requises.',
    options_considered: null,
    decision_made: 'Migration vers le fournisseur B approuvée',
    justification: 'Le fournisseur B offre de meilleures garanties de protection des données et une conformité RGPD vérifiée.',
    residual_risks: null,
    conditions: null,
    impact: 'medium' as const,
    effective_date: '2026-03-01',
    review_date: null,
    risk_assessment_id: null,
    incident_id: null,
    requester_id: 'demo-user-2',
    approver_ids: [],
    status: 'submitted' as const,
    rejection_reason: null,
    approved_at: null,
    implemented_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-18T11:00:00Z',
    updated_at: '2026-01-22T09:00:00Z',
  },
  {
    id: 'demo-dec-4',
    organization_id: 'demo-org',
    title: 'Exception pour utilisation de données synthétiques',
    decision_type: 'exception' as const,
    ai_system_ids: ['demo-sys-4'],
    context: 'L\u2019équipe de traduction souhaite utiliser des données synthétiques pour entraîner le modèle.',
    options_considered: null,
    decision_made: null,
    justification: null,
    residual_risks: null,
    conditions: null,
    impact: 'low' as const,
    effective_date: null,
    review_date: null,
    risk_assessment_id: null,
    incident_id: null,
    requester_id: 'demo-user-1',
    approver_ids: [],
    status: 'draft' as const,
    rejection_reason: null,
    approved_at: null,
    implemented_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-24T15:00:00Z',
    updated_at: '2026-01-24T15:00:00Z',
  },
];

/* ================================================================== */
/*  14. DOCUMENTS                                                      */
/* ================================================================== */

export const DEMO_DOCUMENTS: GovDocument[] = [
  {
    id: 'demo-doc-1',
    organization_id: 'demo-org',
    ai_system_id: null,
    title: 'Politique d\u2019utilisation responsable de l\u2019IA — v2',
    document_type: 'policy',
    description: null,
    file_url: null,
    file_name: 'politique_ia_v2.pdf',
    file_size: 245_000,
    mime_type: 'application/pdf',
    version: 2,
    status: 'approved' as const,
    tags: ['gouvernance', 'IA responsable', 'politique'],
    category: 'policy',
    subcategory: 'ai_usage',
    summary: null,
    ai_analysis: null,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-12-01T09:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'demo-doc-2',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-1',
    title: 'Rapport d\u2019évaluation des risques — Scoring RH',
    document_type: 'assessment',
    description: null,
    file_url: null,
    file_name: 'eval_risques_scoring_rh.pdf',
    file_size: 520_000,
    mime_type: 'application/pdf',
    version: 1,
    status: 'approved' as const,
    tags: ['risque', 'évaluation', 'RH', 'scoring'],
    category: 'assessment',
    subcategory: 'risk_assessment',
    summary: null,
    ai_analysis: null,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-12T14:00:00Z',
    updated_at: '2026-01-18T16:00:00Z',
  },
  {
    id: 'demo-doc-3',
    organization_id: 'demo-org',
    ai_system_id: null,
    title: 'Compte-rendu du comité d\u2019éthique — Janvier 2026',
    document_type: 'meeting',
    description: null,
    file_url: null,
    file_name: 'cr_comite_ethique_jan2026.docx',
    file_size: 128_000,
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    version: 1,
    status: 'in_review' as const,
    tags: ['comité', 'éthique', 'compte-rendu'],
    category: 'meeting',
    subcategory: 'committee_minutes',
    summary: null,
    ai_analysis: null,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-01-21T09:00:00Z',
  },
  {
    id: 'demo-doc-4',
    organization_id: 'demo-org',
    ai_system_id: null,
    title: 'Charte éthique de l\u2019IA générative — brouillon',
    document_type: 'policy',
    description: null,
    file_url: null,
    file_name: 'charte_ethique_genai_draft.pdf',
    file_size: 180_000,
    mime_type: 'application/pdf',
    version: 1,
    status: 'draft' as const,
    tags: ['éthique', 'IA générative', 'charte'],
    category: 'policy',
    subcategory: 'ethics_charter',
    summary: null,
    ai_analysis: null,
    approved_by: null,
    approved_at: null,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-22T13:00:00Z',
    updated_at: '2026-01-25T10:00:00Z',
  },
];

/* ================================================================== */
/*  15. DOCUMENT COUNTS                                                */
/* ================================================================== */

export const DEMO_DOCUMENT_COUNTS = {
  policy: 2,
  assessment: 1,
  meeting: 1,
  training: 0,
  audit: 0,
} as const;

/* ================================================================== */
/*  16. DATASETS                                                       */
/* ================================================================== */

export const DEMO_DATASETS: Dataset[] = [
  {
    id: 'demo-ds-1',
    organization_id: 'demo-org',
    name: 'Historique des candidatures RH',
    description: null,
    ai_system_ids: ['demo-sys-1'],
    source: 'internal_db' as const,
    data_categories: ['Données personnelles', 'Données professionnelles', 'Évaluations'],
    classification: 'personal' as const,
    volume: '10k_100k' as const,
    quality: 'high' as const,
    freshness: 'daily' as const,
    storage_locations: [],
    format: null,
    representativeness: null,
    legal_basis: null,
    declared_purpose: null,
    consent_obtained: true,
    withdrawal_mechanism: null,
    retention_duration: null,
    retention_unit: null,
    retention_justification: null,
    destruction_policy: null,
    next_review_date: null,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'demo-ds-2',
    organization_id: 'demo-org',
    name: 'Logs de transactions financières',
    description: null,
    ai_system_ids: ['demo-sys-3'],
    source: 'internal_db' as const,
    data_categories: ['Données financières', 'Identifiants client'],
    classification: 'sensitive' as const,
    volume: 'gt_1m' as const,
    quality: 'medium' as const,
    freshness: 'realtime' as const,
    storage_locations: [],
    format: null,
    representativeness: null,
    legal_basis: null,
    declared_purpose: null,
    consent_obtained: false,
    withdrawal_mechanism: null,
    retention_duration: null,
    retention_unit: null,
    retention_justification: null,
    destruction_policy: null,
    next_review_date: null,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-06T10:00:00Z',
    updated_at: '2026-01-20T14:00:00Z',
  },
  {
    id: 'demo-ds-3',
    organization_id: 'demo-org',
    name: 'Corpus de traduction bilingue',
    description: null,
    ai_system_ids: ['demo-sys-4'],
    source: 'public_dataset' as const,
    data_categories: ['Textes publics', 'Documents internes anonymisés'],
    classification: 'none' as const,
    volume: '100k_1m' as const,
    quality: 'high' as const,
    freshness: 'monthly' as const,
    storage_locations: [],
    format: null,
    representativeness: null,
    legal_basis: null,
    declared_purpose: null,
    consent_obtained: false,
    withdrawal_mechanism: null,
    retention_duration: null,
    retention_unit: null,
    retention_justification: null,
    destruction_policy: null,
    next_review_date: null,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-08T08:00:00Z',
    updated_at: '2026-01-18T11:00:00Z',
  },
];

/* ================================================================== */
/*  17. DATA TRANSFERS                                                 */
/* ================================================================== */

export const DEMO_DATA_TRANSFERS: DataTransfer[] = [
  {
    id: 'demo-dt-1',
    organization_id: 'demo-org',
    dataset_id: 'demo-ds-2',
    destination_country: 'États-Unis',
    destination_entity: null,
    transfer_purpose: 'Hébergement et traitement par le fournisseur cloud',
    contractual_basis: 'Clauses contractuelles types (CCT)',
    efvp_completed: true,
    protection_measures: null,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-15T11:00:00Z',
  },
];

/* ================================================================== */
/*  18. BIAS FINDINGS                                                  */
/* ================================================================== */

export const DEMO_BIAS_FINDINGS: BiasFinding[] = [
  {
    id: 'demo-bf-1',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-1',
    title: 'Impact disparate sur les candidatures féminines',
    bias_type: 'disparate_impact' as const,
    detection_method: 'automated_test' as const,
    protected_dimensions: ['Genre', 'Âge'],
    affected_groups: null,
    severity: 'high' as const,
    likelihood: null,
    estimated_impact: null,
    affected_count: 342,
    fairness_metric: null,
    measured_value: null,
    acceptable_threshold: null,
    remediation_measures: [],
    remediation_description: null,
    remediation_responsible_id: null,
    remediation_target_date: '2026-03-01',
    remediation_retest_result: null,
    remediation_resolved_at: null,
    status: 'in_remediation' as const,
    decision_id: null,
    detected_by: null,
    detected_at: '2026-01-12T10:00:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-01-20T14:00:00Z',
  },
  {
    id: 'demo-bf-2',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-3',
    title: 'Sous-représentation des transactions internationales',
    bias_type: 'representation' as const,
    detection_method: 'manual_audit' as const,
    protected_dimensions: ['Origine géographique'],
    affected_groups: null,
    severity: 'medium' as const,
    likelihood: null,
    estimated_impact: null,
    affected_count: 1580,
    fairness_metric: null,
    measured_value: null,
    acceptable_threshold: null,
    remediation_measures: [],
    remediation_description: null,
    remediation_responsible_id: null,
    remediation_target_date: '2026-04-15',
    remediation_retest_result: null,
    remediation_resolved_at: null,
    status: 'identified' as const,
    decision_id: null,
    detected_by: null,
    detected_at: '2026-01-18T15:00:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-18T15:00:00Z',
    updated_at: '2026-01-18T15:00:00Z',
  },
  {
    id: 'demo-bf-3',
    organization_id: 'demo-org',
    ai_system_id: 'demo-sys-2',
    title: 'Stéréotypes dans les réponses du chatbot',
    bias_type: 'stereotyping' as const,
    detection_method: 'user_complaint' as const,
    protected_dimensions: ['Genre', 'Origine ethnique'],
    affected_groups: null,
    severity: 'low' as const,
    likelihood: null,
    estimated_impact: null,
    affected_count: 15,
    fairness_metric: null,
    measured_value: null,
    acceptable_threshold: null,
    remediation_measures: [],
    remediation_description: null,
    remediation_responsible_id: null,
    remediation_target_date: null,
    remediation_retest_result: null,
    remediation_resolved_at: '2026-01-22T10:00:00Z',
    status: 'resolved' as const,
    decision_id: null,
    detected_by: null,
    detected_at: '2026-01-10T09:00:00Z',
    created_by: null,
    updated_by: null,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-22T10:00:00Z',
  },
];

/* ================================================================== */
/*  19. VENDORS                                                        */
/* ================================================================== */

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'demo-vnd-1',
    organization_id: 'demo-org',
    name: 'OpenAI',
    service_types: ['LLM Provider'],
    website: null,
    contact_name: null,
    contact_email: null,
    contact_phone: null,
    country: null,
    region: null,
    known_subcontractors: null,
    ai_system_ids: ['demo-sys-2'],
    contract_start_date: null,
    contract_end_date: '2026-12-31',
    contract_type: null,
    contract_amount: null,
    contract_clauses: null,
    sla_details: null,
    risk_level: 'high' as const,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2025-06-01T09:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'demo-vnd-2',
    organization_id: 'demo-org',
    name: 'Dataiku',
    service_types: ['ML Platform'],
    website: null,
    contact_name: null,
    contact_email: null,
    contact_phone: null,
    country: null,
    region: null,
    known_subcontractors: null,
    ai_system_ids: ['demo-sys-1', 'demo-sys-3'],
    contract_start_date: null,
    contract_end_date: '2026-09-30',
    contract_type: null,
    contract_amount: null,
    contract_clauses: null,
    sla_details: null,
    risk_level: 'medium' as const,
    status: 'active' as const,
    created_by: null,
    updated_by: null,
    created_at: '2025-09-15T10:00:00Z',
    updated_at: '2026-01-10T14:00:00Z',
  },
  {
    id: 'demo-vnd-3',
    organization_id: 'demo-org',
    name: 'DeepL',
    service_types: ['Translation API'],
    website: null,
    contact_name: null,
    contact_email: null,
    contact_phone: null,
    country: null,
    region: null,
    known_subcontractors: null,
    ai_system_ids: ['demo-sys-4'],
    contract_start_date: null,
    contract_end_date: '2026-06-30',
    contract_type: null,
    contract_amount: null,
    contract_clauses: null,
    sla_details: null,
    risk_level: 'low' as const,
    status: 'under_review' as const,
    created_by: null,
    updated_by: null,
    created_at: '2025-11-01T08:00:00Z',
    updated_at: '2026-01-20T11:00:00Z',
  },
];
