/**
 * Centralized re-exports for demo data.
 *
 * Usage:
 *   import { DEMO_RISK_ASSESSMENTS, DEMO_COMPLIANCE_SCORES } from '@/portail/demo';
 */

export {
  DEMO_RISK_ASSESSMENTS,
  DEMO_COMPLIANCE_SCORES,
  DEMO_COMPLIANCE_ASSESSMENTS,
  DEMO_REMEDIATION_ACTIONS,
  DEMO_AUTOMATED_DECISIONS,
  DEMO_CONTESTATIONS,
  DEMO_POLICIES,
  DEMO_GOVERNANCE_ROLES,
  DEMO_COMMITTEES,
  DEMO_INCIDENTS,
  DEMO_MONITORING_METRICS,
  DEMO_MONITORING_DATA_POINTS,
  DEMO_DECISIONS,
  DEMO_DOCUMENTS,
  DEMO_DOCUMENT_COUNTS,
  DEMO_DATASETS,
  DEMO_DATA_TRANSFERS,
  DEMO_BIAS_FINDINGS,
  DEMO_VENDORS,
} from './data';
